# Generated by Django 3.2.4 on 2021-06-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producName',
            new_name='product_name',
        ),
    ]
