# Generated by Django 3.2.4 on 2021-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0002_auto_20210628_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
