# Generated by Django 3.2.5 on 2021-07-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0004_order_order_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='order_item',
        ),
    ]
