# Generated by Django 3.2.5 on 2021-07-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
